### PR TITLE
SSN Boston notes, one or two spelling fixes, financial advice

### PR DESCRIPTION
**Pull request by TheKevJames**

### CODE REVIEW

**Comment by sholiday** [comment]
Regarding the fees, there almost always is a fee. Often it's hidden in the rate the bank gives you. Did you compare your rate with the mid market rate?

For example, I have a Canadian TD USD account and I can move money between that and my Canadian TD CAD account. However the rate is worse than offered by xe.com.

**Comment by sholiday** [comment]
I've just check my account (I don't get a preferred rate so yours may be better) but I'm offered 1 USD = 1.014 CAD while Google puts the mid-market rate at 1.04 CAD. (The rate quoted was for 1100 USD)

**Comment by TheKevJames** [comment]
Stephen,

I did a double check. On the day I transfered, the exchange rate was 1.038,
and I got 1.033. As far as I know, I don't have any preferred rates, but we
can add the .5% surcharge.

It may also be related to the amount transferred: I transferred around 30K,
so fees may be waived / reduced somewhere between those amounts.

Kevin

**Comment by sholiday** [comment]
Cool, I just checked for 30,000 (exactly) I get 1.0244 with the mid-market rate at 1.0393.
I have some random account though. If you have something better you will probably get a better rate.
Unfortunately I don't think 30K at a time is feasible for a lot of people.

Perhaps noting that the rate can depend on how much you transfer should be more clear. It's there but it's not that obvious.

**Comment by sholiday** [comment]
Sorry for the delay! It's been hectic. Thanks again for contributing.

**Pull request merged**
