### PR TITLE
added information about visiting outside of country

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by sholiday** [comment]
I think if you leave the country and plan to enter from a country other than Canada you need to send your DS-2019 to Cultural Vistas so they can authorize it for travel.

I had to do this in 2012 and my friend had to do it when he was traveling for work.

Do you know if this is still the case?

**Comment by ghost** [comment]
At the border, they said I just need to show my DS-2019 and I did get detained for not having it... I am not sure what happens if you actually do have it...

**Comment by sholiday** [comment]
Were you entering from Canada or elsewhere?

**Comment by ghost** [comment]
I went to Canada for a couple days and I was at Pearson Airport going back into the States...

**Comment by sholiday** [comment]
I'll add a note that if you are not entering from Canada you need to contact Cultural Vistas for approval / have them stamp your DS-2019.

**Comment by sholiday** [comment]
Thanks for your contribution!

**Pull request merged**
